name: cricketX
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.3.0
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  flutter_dotenv: ^5.2.1
  flutter_animate: ^4.5.2
  lottie: ^3.3.1
  shared_preferences: ^2.5.3
  flutter_cache_manager: ^3.4.1
  firebase_core: ^3.12.1
  firebase_remote_config: ^5.4.2
  provider: ^6.1.4
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_logo.jpg"
  adaptive_icon_background: "#ffffff" # Optional (Android only)

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/.env
    - assets/app_logo.jpg
    - assets/animations/
