// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbHnt-DT_JXwCV6gaMLYkYN2_JahytCpw',
    appId: '1:272946205978:web:7a457f8fe4ed23ce0308a3',
    messagingSenderId: '272946205978',
    projectId: 'cricket-app-6a8fe',
    authDomain: 'cricket-app-6a8fe.firebaseapp.com',
    storageBucket: 'cricket-app-6a8fe.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRU-psj8Z8R1-0iJwUaYvXzpXtJD5Vi-0',
    appId: '1:272946205978:android:e71e0e00d052c1000308a3',
    messagingSenderId: '272946205978',
    projectId: 'cricket-app-6a8fe',
    storageBucket: 'cricket-app-6a8fe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFyHk3nuO1rQyL0qPHR7CUATcG6BVDsbQ',
    appId: '1:272946205978:ios:78779289f3b70e700308a3',
    messagingSenderId: '272946205978',
    projectId: 'cricket-app-6a8fe',
    storageBucket: 'cricket-app-6a8fe.firebasestorage.app',
    iosBundleId: 'com.example.cricketApp',
  );
}
